export interface ServiceShloka {
  devanagari: string;
  transliteration: string;
  source_hi: string;
  source_en: string;
  meaning_hi: string;
  meaning_en: string;
  context_hi: string;
  context_en: string;
}

export const serviceShlokas: Record<string, ServiceShloka> = {
  "griha-pravesh": {
    devanagari: "गृहं प्रविश्य पूजयेत् वास्तुदेवं विधानतः।\nसर्वसिद्धिप्रदं देवं सर्वदोषविनाशनम्॥",
    transliteration: "Grihaṃ praviśya pūjayet vāstadevaṃ vidhānataḥ। Sarvasiddhipradaṃ devaṃ sarvadoṣavināśanam॥",
    source_en: "Skanda Purana, Grihya Kanda",
    source_hi: "स्कन्द पुराण, गृह्य खण्ड",
    meaning_en: "Before entering a new home, one must worship Vastu Devata according to prescribed rites — the deity who grants all success and destroys all doshas.",
    meaning_hi: "नए घर में प्रवेश करने से पहले, विधिपूर्वक वास्तु देवता की पूजा करनी चाहिए — जो सभी सिद्धियाँ प्रदान करते हैं और सभी दोषों का नाश करते हैं।",
    context_en: "This verse is the scriptural basis for Griha Pravesh. Skipping this puja is considered inauspicious — it leaves the home open to Vastu doshas that accumulate over time and affect health, relationships, and prosperity.",
    context_hi: "यह श्लोक गृह प्रवेश का शास्त्रीय आधार है। इस पूजा के बिना गृह प्रवेश अशुभ माना जाता है — वास्तु दोष समय के साथ स्वास्थ्य, संबंध और समृद्धि को प्रभावित करते हैं।",
  },
  "satyanarayan": {
    devanagari: "सत्यनारायणस्य व्रतं पुण्यं पापप्रणाशनम्।\nभुक्तिमुक्तिप्रदं नृणां सर्वसंकटनाशनम्॥",
    transliteration: "Satyanārāyaṇasya vrataṃ puṇyaṃ pāpapraṇāśanam। Bhuktimuktipadaṃ nṛṇāṃ sarvasaṃkaṭanāśanam॥",
    source_en: "Skanda Purana, Reva Khanda (Adhyaya 1)",
    source_hi: "स्कन्द पुराण, रेवा खण्ड (अध्याय १)",
    meaning_en: "The Satyanarayan Vrata is most sacred, it destroys all sins, grants worldly enjoyment and liberation, and removes all sorrows and obstacles for its devotees.",
    meaning_hi: "सत्यनारायण व्रत अत्यंत पुण्यकारी है, समस्त पापों का नाश करता है, भोग और मोक्ष देता है, और भक्तों के सभी संकट दूर करता है।",
    context_en: "Maharshi Suta narrated this Katha to the sages of Naimisharanya forest. When you host this Katha, you become part of an unbroken chain of devotion stretching back thousands of years.",
    context_hi: "महर्षि सूत ने नैमिषारण्य के ऋषियों को यह कथा सुनाई थी। इस कथा का आयोजन करके आप हजारों वर्षों से चली आ रही भक्ति की अटूट परंपरा का हिस्सा बनते हैं।",
  },
  "vivah": {
    devanagari: "शुभे मुहूर्ते विधिवत् कन्यादानं प्रशस्यते।\nसप्तपद्यां कृते विप्र सा भार्या नात्र संशयः॥",
    transliteration: "Śubhe muhūrte vidhivat kanyādānaṃ praśasyate। Saptapadyāṃ kṛte vipra sā bhāryā nātra saṃśayaḥ॥",
    source_en: "Paraskara Grihya Sutra, Adhyaya 1",
    source_hi: "पारस्कर गृह्यसूत्र, अध्याय १",
    meaning_en: "Kanyadaan at an auspicious muhurat, performed according to the Shastra, is most commendable. After the seven steps (Saptapadi) are taken, she is truly and undoubtedly his wife.",
    meaning_hi: "शुभ मुहूर्त में शास्त्रोक्त विधि से कन्यादान सबसे प्रशंसनीय है। सप्तपदी के पूर्ण होने पर वह निःसंदेह उसकी धर्मपत्नी बन जाती है।",
    context_en: "Vivah is the 13th and most significant of the 16 Samskaras. The Saptapadi (seven steps around sacred fire) is the legal and spiritual completion of the marriage — no ceremony is considered complete without it.",
    context_hi: "विवाह 16 संस्कारों में 13वाँ और सबसे महत्वपूर्ण संस्कार है। सप्तपदी (पवित्र अग्नि के चारों ओर सात फेरे) विवाह की कानूनी और आध्यात्मिक परिपूर्णता है — इसके बिना कोई भी समारोह पूर्ण नहीं माना जाता।",
  },
  "rudrabhishek": {
    devanagari: "अभिषेकं प्रकुर्वीत शिवलिङ्गस्य भक्तितः।\nश्रीरुद्रमन्त्रपाठेन सर्वपापैः प्रमुच्यते॥",
    transliteration: "Abhiṣekaṃ prakurvīta śivaliṅgasya bhaktitaḥ। Śrīrudramantrapaṭhena sarvapāpaiḥ pramucyate॥",
    source_en: "Shiva Purana, Vidyeshvara Samhita",
    source_hi: "शिव पुराण, विद्येश्वर संहिता",
    meaning_en: "One who performs Abhishek of the Shivalinga with devotion, while chanting the Shri Rudra mantras, is freed from all sins.",
    meaning_hi: "जो व्यक्ति भक्तिभाव से शिवलिंग का अभिषेक करता है और श्री रुद्र मंत्रों का पाठ करता है, वह समस्त पापों से मुक्त हो जाता है।",
    context_en: "The Shri Rudram from the Yajurveda is one of the oldest Sanskrit hymns. Recited by Pandit Ji during Rudrabhishek, each verse directly pacifies the corresponding Navagraha and dissolves karmic blockages.",
    context_hi: "यजुर्वेद का श्री रुद्रम सबसे प्राचीन संस्कृत स्तोत्रों में से एक है। रुद्राभिषेक के दौरान पंडित जी द्वारा पाठ किए जाने पर, प्रत्येक श्लोक संबंधित नवग्रह को शांत करता है और कर्म बाधाओं को दूर करता है।",
  },
  "namkaran": {
    devanagari: "नामकर्म द्विजातीनां जन्मतो दशमेऽहनि।\nशुभनक्षत्रयुक्ते तु शुभं नाम प्रदापयेत्॥",
    transliteration: "Nāmakarma dvijātīnāṃ janmato daśame'hani। Śubhanakṣatrayukte tu śubhaṃ nāma pradāpayet॥",
    source_en: "Ashvalayana Grihya Sutra, Adhyaya 1",
    source_hi: "आश्वलायन गृह्यसूत्र, अध्याय १",
    meaning_en: "Namakaran (the naming rite) for the twice-born should be performed on the 10th day from birth, choosing an auspicious name aligned with the birth Nakshatra.",
    meaning_hi: "द्विजों का नामकरण जन्म के दसवें दिन किया जाना चाहिए, जन्म नक्षत्र के अनुकूल शुभ नाम रखा जाना चाहिए।",
    context_en: "A name given through Namkaran is not just a label — it is a spiritual identity rooted in the child's birth Nakshatra and Rashi. This name carries vibrational energy that shapes the child's destiny.",
    context_hi: "नामकरण से दिया गया नाम केवल एक पहचान नहीं है — यह बच्चे के जन्म नक्षत्र और राशि में निहित एक आध्यात्मिक पहचान है। यह नाम एक कंपनात्मक ऊर्जा वहन करता है जो बच्चे के भाग्य को आकार देती है।",
  },
  "mundan": {
    devanagari: "चूडाकर्म तृतीये वर्षे कर्तव्यं नित्यमेव हि।\nमस्तिष्कस्य विशुद्ध्यर्थं पूर्वपुण्यस्य शोधनम्॥",
    transliteration: "Cūḍākarma tṛtīye varṣe kartavyaṃ nityameva hi। Mastiṣkasya viśuddhyarthaṃ pūrvapuṇyasya śodhanam॥",
    source_en: "Manusmriti 2.35, Grihya Sutras",
    source_hi: "मनुस्मृति २.३५, गृह्य सूत्र",
    meaning_en: "Chudakarana (Mundan) should be performed in the third year of life for the purification of the brain and the cleansing of the merits and demerits of past lives.",
    meaning_hi: "मस्तिष्क की शुद्धि और पूर्व जन्म के पुण्य-पाप के शोधन के लिए चूड़ाकर्म तीसरे वर्ष में करना चाहिए।",
    context_en: "Mundan is not merely a haircut — it is the removal of the hair that carried the vibrations of the womb and past-life karmas, giving the child a clean spiritual slate for this lifetime.",
    context_hi: "मुंडन केवल बाल काटना नहीं है — यह उस केश को हटाना है जो गर्भ और पूर्वजन्म के कर्मों की तरंगें वहन करता था, जिससे बच्चे को इस जीवन के लिए एक स्वच्छ आध्यात्मिक आरम्भ मिलता है।",
  },
  "ganesh-puja": {
    devanagari: "वक्रतुण्ड महाकाय सूर्यकोटिसमप्रभ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
    transliteration: "Vakratuṇḍa mahākāya sūryakoṭisamaprabha। Nirvighnaṃ kuru me deva sarvakāryeṣu sarvadā॥",
    source_en: "Ganesha Purana, Upasana Khanda",
    source_hi: "गणेश पुराण, उपासना खण्ड",
    meaning_en: "O Ganesha with the curved trunk and mighty form, radiant as a crore suns — grant me freedom from all obstacles in everything I do, always.",
    meaning_hi: "हे वक्रतुण्ड, महाकाय, करोड़ सूर्यों के समान तेजस्वी गणेश — मेरे सभी कार्यों में सदा निर्विघ्नता प्रदान करें।",
    context_en: "No auspicious work — Griha Pravesh, Vivah, business launch, or exam — is started without first invoking Ganesha. The Mudgala Purana states that Ganesha is worshipped before all gods in all four Vedic traditions.",
    context_hi: "कोई भी शुभ कार्य — गृह प्रवेश, विवाह, व्यापार आरम्भ या परीक्षा — गणेश आह्वान के बिना शुरू नहीं होता। मुद्गल पुराण कहता है कि चारों वेद परंपराओं में गणेश को सर्वप्रथम पूजा जाता है।",
  },
  "lakshmi-puja": {
    devanagari: "हिरण्यवर्णां हरिणीं सुवर्णरजतस्रजाम्।\nचन्द्रां हिरण्मयीं लक्ष्मीं जातवेदो म आवह॥",
    transliteration: "Hiraṇyavarṇāṃ hariṇīṃ suvarṇarajatasrajām। Candrāṃ hiraṇmayīṃ lakṣmīṃ jātavedo ma āvaha॥",
    source_en: "Shri Sukta, Rigveda (Khilani, First Verse)",
    source_hi: "श्री सूक्त, ऋग्वेद (प्रथम मंत्र)",
    meaning_en: "O Jataveda! Bring to me Lakshmi — golden-hued, deer-eyed, adorned with garlands of gold and silver, radiant as the moon, the embodiment of abundance.",
    meaning_hi: "हे जातवेद! सुवर्ण वर्णा, हरिण-नेत्री, सोने-चाँदी की मालाओं से सुशोभित, चन्द्रमा-सी दीप्तिमयी, ऐश्वर्य की प्रतीक लक्ष्मी को मेरे पास लाइए।",
    context_en: "The Shri Sukta is the oldest hymn to Lakshmi, found in the Rigveda — over 3,500 years old. When Pandit Ji chants it during your puja, it is not a mere prayer; it is a precise Vedic invocation that has been used by every generation of Brahmin families to attract prosperity.",
    context_hi: "श्री सूक्त लक्ष्मी का सबसे प्राचीन स्तोत्र है, जो ऋग्वेद में पाया जाता है — 3,500 वर्ष से भी पुराना। जब पंडित जी आपकी पूजा में इसका पाठ करते हैं, तो यह केवल प्रार्थना नहीं है; यह एक सटीक वैदिक आह्वान है जो पीढ़ियों से ब्राह्मण परिवारों द्वारा समृद्धि को आकर्षित करने के लिए प्रयोग किया जाता रहा है।",
  },
  "navgrah-puja": {
    devanagari: "ब्रह्मा मुरारिः त्रिपुरान्तकारी भानुः शशी भूमिसुतो बुधश्च।\nगुरुश्च शुक्रः शनिराहुकेतवः कुर्वन्तु सर्वे मम सुप्रभातम्॥",
    transliteration: "Brahmā murāriḥ tripurāntakārī bhānuḥ śaśī bhūmisuto budhaśca। Guruśca śukraḥ śanirāhuketavaḥ kurvantu sarve mama suprapaātam॥",
    source_en: "Matsya Purana, Navagraha Adhyaya",
    source_hi: "मत्स्य पुराण, नवग्रह अध्याय",
    meaning_en: "May Brahma, Vishnu, Shiva, the Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu and Ketu — all these nine cosmic forces — bless my every morning with auspiciousness.",
    meaning_hi: "ब्रह्मा, विष्णु, शिव, सूर्य, चन्द्र, मंगल, बुध, बृहस्पति, शुक्र, शनि, राहु और केतु — ये सभी नव कॉस्मिक शक्तियाँ मेरी हर सुबह को शुभ बनाएं।",
    context_en: "The nine planets govern every aspect of human life — health, career, relationships, and fortune. When their influence is malefic due to Kundali doshas, no external effort alone can overcome it. Navgraha Puja, prescribed in the Matsya Purana, directly balances these cosmic forces.",
    context_hi: "नौ ग्रह मानव जीवन के प्रत्येक पहलू — स्वास्थ्य, करियर, सम्बन्ध और भाग्य — को नियंत्रित करते हैं। जब कुंडली दोष के कारण उनका प्रभाव नकारात्मक हो, तो केवल बाहरी प्रयास से इसे नहीं जीता जा सकता। मत्स्य पुराण में वर्णित नवग्रह पूजा सीधे इन ब्रह्मांडीय शक्तियों को संतुलित करती है।",
  },
  "vastu-shanti": {
    devanagari: "वास्तोष्पते प्रति जानीह्यस्मान् स्वावेशो अनमीवो भवा नः।\nयत् त्वेमहे प्रति तन्नो जुषस्व शं नो भव द्विपदे शं चतुष्पदे॥",
    transliteration: "Vāstoṣpate prati jānīhyasmān svāveśo anamīvo bhavā naḥ। Yat tvemahe prati tan no juṣasva śaṃ no bhava dvipade śaṃ catuṣpade॥",
    source_en: "Rigveda 7.54.1 (Vastu Sukta)",
    source_hi: "ऋग्वेद ७.५४.१ (वास्तु सूक्त)",
    meaning_en: "O Vastu Pati (Lord of the dwelling), recognise us as your own; be free from disease in our home. Accept our prayers and be auspicious to our two-legged and four-legged beings.",
    meaning_hi: "हे वास्तु पति, हमें अपना मानो; हमारे घर में रोग-मुक्त रहो। हमारी प्रार्थना स्वीकार करो और हमारे द्विपाद और चतुष्पाद सभी प्राणियों के लिए कल्याणकारी बनो।",
    context_en: "The Vastu Sukta of the Rigveda is over 3,000 years old. It is the most ancient Vedic prayer for harmonising the energy of a dwelling place. Modern Vastu Shanti Puja is rooted in this very sukta, making it not superstition but a time-tested Vedic science.",
    context_hi: "ऋग्वेद का वास्तु सूक्त 3,000 वर्ष से भी अधिक पुराना है। यह किसी आवास की ऊर्जा को संतुलित करने के लिए सबसे प्राचीन वैदिक प्रार्थना है। आधुनिक वास्तु शांति पूजा इसी सूक्त में निहित है, जो इसे अंधविश्वास नहीं बल्कि एक समय-परीक्षित वैदिक विज्ञान बनाती है।",
  },
  "kanya-puja": {
    devanagari: "यत्र नार्यस्तु पूज्यन्ते रमन्ते तत्र देवताः।\nयत्रैतास्तु न पूज्यन्ते सर्वास्तत्राफलाः क्रियाः॥",
    transliteration: "Yatra nāryastu pūjyante ramante tatra devatāḥ। Yatraitāstu na pūjyante sarvāstatrāphalāḥ kriyāḥ॥",
    source_en: "Manusmriti 3.56",
    source_hi: "मनुस्मृति ३.५६",
    meaning_en: "Where women are honoured, there the gods rejoice. Where they are not honoured, all rites there become fruitless.",
    meaning_hi: "जहाँ नारी का सम्मान होता है, वहाँ देवता प्रसन्न रहते हैं। जहाँ उनका सम्मान नहीं होता, वहाँ के सभी धार्मिक कार्य निष्फल हो जाते हैं।",
    context_en: "Kanya Puja, performed on Ashtami and Navami of Navratri, embodies this ancient truth from Manusmriti. By worshipping young girls as living manifestations of Devi, the family invites the direct grace of the nine Shaktis into their home.",
    context_hi: "नवरात्रि की अष्टमी और नवमी को की जाने वाली कन्या पूजा मनुस्मृति के इस प्राचीन सत्य को मूर्त रूप देती है। युवा कन्याओं को देवी के जीवित रूप के रूप में पूजने से परिवार अपने घर में नव शक्तियों की सीधी कृपा को आमंत्रित करता है।",
  },
  "annaprashan": {
    devanagari: "अन्नं ब्रह्म इति व्यजानात्। अन्नाद्धि भूतानि जायन्ते।\nजातान्यन्नेन वर्धन्ते। अन्नं प्राणा इति।।",
    transliteration: "Annaṃ brahma iti vyajānāt। Annāddhi bhūtāni jāyante। Jātānyanena vardhante। Annaṃ prāṇā iti।",
    source_en: "Taittiriya Upanishad 3.2",
    source_hi: "तैत्तिरीय उपनिषद् ३.२",
    meaning_en: "He knew Annam (food) as Brahman. From food, indeed, are born all beings. By food, when born, do they live. Into food do they pass at their end.",
    meaning_hi: "उन्होंने अन्न को ब्रह्म के रूप में जाना। अन्न से ही सभी प्राणी उत्पन्न होते हैं। जन्म लेकर वे अन्न से ही जीते हैं। और अंत में अन्न में ही समा जाते हैं।",
    context_en: "Annaprashan, the first solid feeding ceremony, is not a mere milestone — it is the recognition of food as Brahman entering the child's life. The Taittiriya Upanishad's Annavalli chapter is recited during the ceremony, consecrating the very first morsel with Vedic vibrations.",
    context_hi: "अन्नप्राशन, पहला ठोस आहार संस्कार, केवल एक पड़ाव नहीं है — यह बच्चे के जीवन में अन्नरूपी ब्रह्म के प्रवेश की स्वीकृति है। इस संस्कार में तैत्तिरीय उपनिषद् के अन्नवल्ली अध्याय का पाठ किया जाता है, जो पहले ग्रास को ही वैदिक तरंगों से अभिमंत्रित करता है।",
  },
  "yagyopaveet": {
    devanagari: "यज्ञोपवीतं परमं पवित्रं प्रजापतेर्यत्सहजं पुरस्तात्।\nआयुष्यमग्र्यं प्रतिमुञ्च शुभ्रं यज्ञोपवीतं बलमस्तु तेजः॥",
    transliteration: "Yajñopavītaṃ paramaṃ pavitraṃ prajāpateryatsahajaṃ purastāt। Āyuṣyamagryaṃ pratimuñca śubhraṃ yajñopavītaṃ balmastu tejaḥ॥",
    source_en: "Yagyopaveet Mantra (Paraskara Grihya Sutra 2.2)",
    source_hi: "यज्ञोपवीत मंत्र (पारस्कर गृह्यसूत्र २.२)",
    meaning_en: "I put on the sacred thread — the supreme purifier, born with Prajapati at the beginning of creation. May this pure, white sacred thread grant me long life, strength, and radiance.",
    meaning_hi: "मैं यज्ञोपवीत धारण करता हूँ — सर्वोच्च पवित्रकर्ता, जो सृष्टि के प्रारंभ में प्रजापति के साथ उत्पन्न हुआ। यह शुभ्र यज्ञोपवीत मुझे दीर्घायु, बल और तेज प्रदान करे।",
    context_en: "Yagyopaveet (Janeu/Upanayana) marks a boy's second birth — his entry into the Vedic student life (Brahmacharya). The sacred thread is prescribed precisely in the Paraskara Grihya Sutra, the same text in which our Pandit Ji is trained. This is not ritual theatre; it is a lifelong vow.",
    context_hi: "यज्ञोपवीत (जनेऊ/उपनयन) एक बालक का द्वितीय जन्म है — वैदिक छात्र जीवन (ब्रह्मचर्य) में प्रवेश। यह पवित्र धागा पारस्कर गृह्यसूत्र में ठीक-ठीक बताया गया है — वही ग्रंथ जिसमें हमारे पंडित जी प्रशिक्षित हैं। यह केवल रस्म नहीं; यह आजीवन संकल्प है।",
  },
  "mangal-dosh": {
    devanagari: "मङ्गलं भगवान् विष्णुः मङ्गलं गरुडध्वजः।\nमङ्गलं पुण्डरीकाक्षो मङ्गलायतनं हरिः॥",
    transliteration: "Maṅgalaṃ Bhagavān Viṣṇuḥ maṅgalaṃ Garuḍadhvajaḥ। Maṅgalaṃ Puṇḍarīkākṣo maṅgalāyatanaṃ Hariḥ॥",
    source_en: "Vishnu Purana, Mangalacharana",
    source_hi: "विष्णु पुराण, मंगलाचरण",
    meaning_en: "Bhagavan Vishnu is the embodiment of auspiciousness. Garuda-bannered Vishnu is auspiciousness. The lotus-eyed one is auspicious. Hari is the abode of all that is good and auspicious.",
    meaning_hi: "भगवान विष्णु मंगल के स्वरूप हैं। गरुड़ध्वज विष्णु मंगल हैं। पुण्डरीकाक्ष मंगल हैं। हरि समस्त मंगल का आयतन हैं।",
    context_en: "Mangal Dosha Shanti Puja invokes Vishnu and specifically the Mars deity (Mangal) to neutralise planetary maleficence. Jyotisha Shastra classifies Mangal as both a Graha (planet) and a devata whose worship directly modifies karmic outcomes when performed with Shastreey precision.",
    context_hi: "मंगल दोष शांति पूजा विष्णु और विशेष रूप से मंगल देव का आह्वान करती है। ज्योतिष शास्त्र मंगल को एक ग्रह और देवता दोनों रूपों में वर्गीकृत करता है, जिनकी शास्त्रीय विधि से की गई पूजा कर्मफल को प्रत्यक्ष रूप से संशोधित करती है।",
  },
  "kaal-sarp-dosh": {
    devanagari: "सर्पाणां च प्रणेतारं तक्षकं च महाभुजम्।\nनागान्तकं च वासुकिं पूजयेत् सर्पनाशनम्॥",
    transliteration: "Sarpāṇāṃ ca praṇetāraṃ takṣakaṃ ca mahābhujam। Nāgāntakaṃ ca vāsukiṃ pūjayet sarpa-nāśanam॥",
    source_en: "Narada Purana, Sarpa Puja Adhyaya",
    source_hi: "नारद पुराण, सर्प पूजा अध्याय",
    meaning_en: "One should worship Takshaka, the mighty-armed leader of serpents, Vasuki the serpent-slayer, to remove all effects of Sarpa doshas.",
    meaning_hi: "सर्पदोष के सभी प्रभावों को दूर करने के लिए महाभुज सर्पों के नेता तक्षक और वासुकि की पूजा करनी चाहिए।",
    context_en: "Kaal Sarp Dosh occurs when all seven planets are hemmed between Rahu and Ketu in the birth chart. The Vedic remedy is precise — specific Naga mantras, Rudrabhishek, and Sarpa Sukta from the Rigveda. Our Pandit Ji performs this with authentic Shukla Yajurveda mantras.",
    context_hi: "काल सर्प दोष तब होता है जब सभी सात ग्रह कुंडली में राहु और केतु के बीच स्थित हों। वैदिक उपाय सटीक है — विशेष नाग मंत्र, रुद्राभिषेक और ऋग्वेद का सर्प सूक्त। हमारे पंडित जी यह शुक्ल यजुर्वेद मंत्रों के साथ प्रामाणिक रूप से करते हैं।",
  },
  "hanuman-puja": {
    devanagari: "मनोजवं मारुततुल्यवेगं जितेन्द्रियं बुद्धिमतां वरिष्ठम्।\nवातात्मजं वानरयूथमुख्यं श्रीरामदूतं शिरसा नमामि॥",
    transliteration: "Manojaṃ mārutatulyavegaṃ jitendriyaṃ buddhimatāṃ variṣṭham। Vātātmajaṃ vānarayūthamukhyaṃ Śrīrāmadūtaṃ śirasā namāmi॥",
    source_en: "Valmiki Ramayana, Sundarkand (Hanuman Stuti)",
    source_hi: "वाल्मीकि रामायण, सुंदरकांड (हनुमान स्तुति)",
    meaning_en: "I bow to Sri Rama's messenger — swift as the mind and wind, master of his senses, foremost among the wise, son of Vayu, chief of the Vanara hosts.",
    meaning_hi: "श्रीराम के दूत को शिर नमन — मन और वायु की गति वाले, जितेन्द्रिय, बुद्धिमानों में श्रेष्ठ, वायु-पुत्र, वानर-यूथ के मुखिया।",
    context_en: "Hanuman Puja is the most powerful remedy for all forms of fear, debt, black magic, and obstacles. The Sundarkand, recited as part of Hanuman Puja, is a complete spiritual journey — Hanuman's Lanka voyage — that when heard with full faith, removes every obstacle the devotee faces.",
    context_hi: "हनुमान पूजा भय, ऋण, काला जादू और बाधाओं के सभी रूपों का सबसे शक्तिशाली उपाय है। हनुमान पूजा के भाग के रूप में सुंदरकांड का पाठ एक पूर्ण आध्यात्मिक यात्रा है — हनुमान की लंका-यात्रा — जो पूर्ण श्रद्धा के साथ सुनने पर भक्त के सामने आने वाली हर बाधा को दूर करती है।",
  },
  "durga-puja": {
    devanagari: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके।\nशरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥",
    transliteration: "Sarvamangalamāṅgalye śive sarvārthasādhike। Śaraṇye tryambake gauri nārāyaṇi namo'stu te॥",
    source_en: "Durga Saptashati (Markandeya Purana), Chapter 11",
    source_hi: "दुर्गा सप्तशती (मार्कण्डेय पुराण), अध्याय ११",
    meaning_en: "O auspicious one, cause of all auspiciousness, O Shiva, O fulfiller of all desires, O refuge, O three-eyed Gauri, O Narayani — salutations to you.",
    meaning_hi: "हे सर्व मंगलों की मंगला, हे शिवे, हे सर्व अर्थों की साधिका, हे शरण्या, हे त्र्यम्बके गौरि, हे नारायणी — तुम्हें प्रणाम।",
    context_en: "The Durga Saptashati (700 verses to Durga) is the supreme Shakti scripture. When Pandit Ji recites all 700 verses during Durga Puja, it is an invocation of the full Shakti that created, sustains, and dissolves the universe. The Saptashati is prescribed for prosperity, protection, and removal of enemies and obstacles.",
    context_hi: "दुर्गा सप्तशती (दुर्गा की 700 श्लोकों में स्तुति) परम शक्ति ग्रंथ है। जब पंडित जी दुर्गा पूजा के दौरान सभी 700 श्लोकों का पाठ करते हैं, तो यह उस पूर्ण शक्ति का आह्वान है जो ब्रह्मांड का सृजन, पालन और संहार करती है।",
  },
  "saraswati-puja": {
    devanagari: "या कुन्देन्दुतुषारहारधवला या शुभ्रवस्त्रावृता।\nया वीणावरदण्डमण्डितकरा या श्वेतपद्मासना॥",
    transliteration: "Yā kundendustuṣārahāradhavalā yā śubhravastrāvṛtā। Yā vīṇāvaradaṇḍamaṇḍitakarā yā śvetapadmāsanā॥",
    source_en: "Saraswati Vandana (Saraswati Purana)",
    source_hi: "सरस्वती वंदना (सरस्वती पुराण)",
    meaning_en: "She who is white as jasmine, the moon, snow and pearl necklaces; robed in pure white; whose hands are adorned with the Veena and blessing staff; who is seated on a white lotus.",
    meaning_hi: "जो कुंद, चन्द्रमा, हिम और मोतियों की माला जैसी श्वेत हैं; श्वेत वस्त्र धारण करती हैं; जिनके हाथ वीणा और वरदंड से सुशोभित हैं; जो श्वेत कमल पर आसीन हैं।",
    context_en: "Saraswati Puja on Basant Panchami is the most auspicious day for initiating children into learning. According to Skanda Purana, a child who receives Vidyarambha (first writing lesson) on Basant Panchami with Saraswati's blessings never loses her grace throughout life.",
    context_hi: "बसंत पंचमी पर सरस्वती पूजा बच्चों को विद्यारम्भ के लिए सबसे शुभ दिन है। स्कन्द पुराण के अनुसार, जो बालक बसंत पंचमी पर सरस्वती के आशीर्वाद से विद्यारम्भ (प्रथम लेखन पाठ) करता है, वह जीवन भर उनकी कृपा से वंचित नहीं होता।",
  },
  "bhagvat-mahapuran": {
    devanagari: "श्रीमद्भागवतं पुराणममलं यद्वैष्णवानां प्रियम्।\nयस्मिन्पारमहंस्यमेकममलं ज्ञानं परं गीयते॥",
    transliteration: "Śrīmadbhāgavataṃ purāṇamamalaṃ yadvaiṣṇavānāṃ priyam। Yasminpāramahaṃsyamekamamalaṃ jñānaṃ paraṃ gīyate॥",
    source_en: "Shrimad Bhagavat Mahapurana 12.13.18",
    source_hi: "श्रीमद्भागवत महापुराण १२.१३.१८",
    meaning_en: "The Shrimad Bhagavatam, the immaculate Purana, is the most beloved of all Vaishnavas. In it is sung the supreme, pure knowledge of the Paramahamsas.",
    meaning_hi: "श्रीमद्भागवत, निर्मल पुराण, समस्त वैष्णवों का सबसे प्रिय ग्रंथ है। इसमें परमहंसों के परम शुद्ध ज्ञान का गान किया गया है।",
    context_en: "A seven-day Bhagavat Katha is one of the most powerful Vedic events a family can host. The Bhagavata Purana itself declares that the hearing of one complete Saptaha (seven-day recitation) with faith grants Moksha. Our Pandit Ji conducts this from the original Sanskrit with full Vyasasana rituals.",
    context_hi: "सात दिवसीय भागवत कथा एक परिवार द्वारा आयोजित किए जाने वाले सबसे शक्तिशाली वैदिक अनुष्ठानों में से एक है। भागवत पुराण स्वयं घोषित करता है कि श्रद्धा के साथ एक पूर्ण सप्ताह पाठ (सात दिवसीय पाठ) का श्रवण मोक्ष प्रदान करता है।",
  },
  "sundarkand": {
    devanagari: "ततो रावणनीतायाः सीतायाः शत्रुकर्षणः।\nईयेष पदमन्वेष्टुं चारणाचरिते पथि॥",
    transliteration: "Tato rāvaṇanītāyāḥ sītāyāḥ śatrukārṣaṇaḥ। Īyeṣa padamanveṣṭuṃ cāraṇācarite pathi॥",
    source_en: "Valmiki Ramayana, Sundara Kanda 1.1",
    source_hi: "वाल्मीकि रामायण, सुंदरकाण्ड १.१",
    meaning_en: "Then that slayer of enemies set out to find the footsteps of Sita who had been abducted by Ravana — travelling along the path trodden by the Charanas (celestial bards).",
    meaning_hi: "तब उस शत्रुकर्षण (हनुमान) ने रावण द्वारा हरी गई सीता के पदचिह्नों की खोज में प्रस्थान किया — चारणों द्वारा विचरित मार्ग से।",
    context_en: "Sundarkand (Chapter 5 of Valmiki Ramayana) opens with Hanuman's leap across the ocean — the greatest act of devotion in the Ramayana. Its recitation is prescribed for removal of fear, court cases, health problems, and obstacles. When performed with proper Vedic rites, it is held equal to Rudrabhishek in its power.",
    context_hi: "सुंदरकांड (वाल्मीकि रामायण का 5वाँ अध्याय) हनुमान की समुद्र पार छलांग से शुरू होता है — रामायण में भक्ति का सबसे महान कार्य। इसका पाठ भय, मुकदमों, स्वास्थ्य समस्याओं और बाधाओं के निवारण के लिए निर्धारित है।",
  },
  "ram-katha": {
    devanagari: "श्रीरामचन्द्रं भजे भजे भजे।\nभवाब्धितारणकारणं भजे।\nसदैव रामं रघुनाथमव्ययं।\nभजे भजे भजे भजे भजे॥",
    transliteration: "Śrī Rāmacandraṃ bhaje bhaje bhaje। Bhavābdhitāraṇakāraṇaṃ bhaje। Sadaiva Rāmaṃ Raghunāthamavyayaṃ। Bhaje bhaje bhaje bhaje bhaje॥",
    source_en: "Ramabhujanga Prayata Stotram (Adi Shankaracharya)",
    source_hi: "रामभुजंग प्रयात स्तोत्र (आदि शंकराचार्य)",
    meaning_en: "I worship, worship, worship Sri Ramachandra — the cause of crossing the ocean of existence. I ever worship the eternal Rama, the Lord of the Raghus.",
    meaning_hi: "मैं श्रीरामचंद्र की पूजा करता हूँ, पूजा करता हूँ, पूजा करता हूँ — भव-सागर से तारने वाले। मैं सदा अव्यय राम, रघुनाथ की पूजा करता हूँ।",
    context_en: "Ram Katha is the recitation of the divine story of Rama — the perfect human being according to the Vedic ideal. Hosting a Ram Katha is considered as meritorious as performing an Ashvamedha Yagna. The Valmiki Ramayana has 24,000 verses; our Pandit Ji selects the complete Bal Kanda, Sundarkand and Uttarkanda for the seven-day Katha.",
    context_hi: "राम कथा राम की दिव्य कहानी का वाचन है — वैदिक आदर्श के अनुसार परम मानव। राम कथा का आयोजन करना अश्वमेध यज्ञ करने के समान पुण्यकारी माना जाता है।",
  },
  "shiv-mahapuran": {
    devanagari: "नमः शम्भवाय च मयोभवाय च नमः शङ्कराय च मयस्कराय च।\nनमः शिवाय च शिवतराय च॥",
    transliteration: "Namaḥ śambhavāya ca mayobhavāya ca namaḥ śaṅkarāya ca mayaskarāya ca। Namaḥ śivāya ca śivatarāya ca॥",
    source_en: "Krishna Yajurveda, Taittiriya Samhita 4.5.8 (Namakam / Shri Rudram)",
    source_hi: "कृष्ण यजुर्वेद, तैत्तिरीय संहिता ४.५.८ (नमकम्ᳫ / श्री रुद्रम्)",
    meaning_en: "Salutations to the one who is a source of all happiness; salutations to the one who is beneficial; salutations to Shankara; salutations to Shiva and to the one who is even more auspicious.",
    meaning_hi: "जो सभी सुखों का स्रोत है उसे नमन; जो कल्याणकारी है उसे नमन; शंकर को नमन; शिव को और जो और भी अधिक शुभ है उसे नमन।",
    context_en: "Shiv Mahapuran Katha is the seven-day recitation of all 24,000 shlokas of the Shiva Purana. It is held equal to the merit of a thousand Rudrabhisheks. Families who host this Katha invite Shiva's direct presence into their home, removing all Shani, Rahu-Ketu, and Pitra doshas simultaneously.",
    context_hi: "शिव महापुराण कथा शिव पुराण के सभी 24,000 श्लोकों का सात दिवसीय वाचन है। यह एक हजार रुद्राभिषेक के पुण्य के समान माना जाता है। इस कथा का आयोजन करने वाले परिवार शिव की प्रत्यक्ष उपस्थिति को अपने घर में आमंत्रित करते हैं।",
  },
  "devi-bhagvat": {
    devanagari: "सर्वाबाधाप्रशमनं त्रैलोक्यस्याखिलेश्वरि।\nएवमेव त्वया कार्यमस्मद्वैरिविनाशनम्॥",
    transliteration: "Sarvābādhāpraśamanaṃ trailokyasyākhileśvari। Evameva tvayā kāryamasmadvairivināśanam॥",
    source_en: "Devi Bhagavat Mahapurana 5.9.15",
    source_hi: "देवी भागवत महापुराण ५.९.१५",
    meaning_en: "O Universal Goddess, the destroyer of all obstacles in all three worlds — may you destroy our enemies in the same way.",
    meaning_hi: "हे त्रैलोक्य की सर्वेश्वरी, सभी बाधाओं की शांति करने वाली — इसी प्रकार हमारे शत्रुओं का नाश करो।",
    context_en: "Devi Bhagavat Mahapuran (18,000 verses) is the supreme scriptural authority on Shakti worship. Hosting a seven-day Devi Bhagavat Katha is the most powerful Navratri offering a family can make. It invokes Mahalakshmi, Mahasaraswati, and Mahakali simultaneously.",
    context_hi: "देवी भागवत महापुराण (18,000 श्लोक) शक्ति उपासना का परम शास्त्रीय प्रमाण है। सात दिवसीय देवी भागवत कथा का आयोजन एक परिवार की ओर से सबसे शक्तिशाली नवरात्रि भेंट है।",
  },
  "akhand-ramayan": {
    devanagari: "रामं दशरथं विद्धि मां विद्धि जनकात्मजाम्।\nअयोध्यामटवीं विद्धि गच्छ तात यथासुखम्॥",
    transliteration: "Rāmaṃ daśarathaṃ viddhi māṃ viddhi janakātmajām। Ayodhyāmaṭavīṃ viddhi gaccha tāta yathāsukham॥",
    source_en: "Valmiki Ramayana 2.52.84",
    source_hi: "वाल्मीकि रामायण २.५२.८४",
    meaning_en: "Know Rama as Dasharatha; know me as Janaka's daughter; know the forest as Ayodhya — then go, my child, as you please.",
    meaning_hi: "राम को दशरथ समझो, मुझे जनककुमारी समझो, इस वन को अयोध्या समझो — तब हे पुत्र, जैसा सुख हो जाओ।",
    context_en: "Akhand Ramayan is the non-stop recitation of all 24,000 verses of Valmiki Ramayana in 24 hours. It is one of the most powerful puja-events that a family can host. According to Uttarkanda, the home in which Ramayan is heard never faces poverty, disease, or untimely death.",
    context_hi: "अखण्ड रामायण वाल्मीकि रामायण के सभी 24,000 श्लोकों का 24 घंटों में अविराम पाठ है। यह एक परिवार द्वारा आयोजित किए जाने वाले सबसे शक्तिशाली पूजा-आयोजनों में से एक है।",
  },
  "sagai": {
    devanagari: "धर्मेण सह धर्मिण्या पाणिं गृह्णीष्व पाणिना।\nसौम्यां जरदष्टिं पतिलोकमभिजित्य।।",
    transliteration: "Dharmeṇa saha dharmiṇyā pāṇiṃ gṛhṇīṣva pāṇinā। Saumyāṃ jaradaṣṭiṃ patilokamabhijitya॥",
    source_en: "Rigveda 10.85.36 (Vivah Sukta)",
    source_hi: "ऋग्वेद १०.८५.३६ (विवाह सूक्त)",
    meaning_en: "Take her hand with your hand in dharma; may she be gentle and long-lived, conquering her husband's world together.",
    meaning_hi: "धर्म के साथ उसका हाथ अपने हाथ में ग्रहण करो; वह सौम्य और दीर्घायु हो, पति-लोक को साथ मिलकर जीते।",
    context_en: "Sagai (Ring Ceremony/Tilak) is the formal Vedic commitment before Vivah. The Rigveda's Vivah Sukta prescribes the exact sequence of promises made at this stage. Our Pandit Ji ensures this ceremony follows the Baudhayana Grihya Sutra so the Vivah Muhurat later flows from a properly established foundation.",
    context_hi: "सगाई (अंगूठी समारोह/तिलक) विवाह से पहले औपचारिक वैदिक प्रतिबद्धता है। ऋग्वेद का विवाह सूक्त इस चरण में की जाने वाली प्रतिज्ञाओं का सटीक क्रम निर्धारित करता है।",
  },
  "navratri-puja": {
    devanagari: "शरणागतदीनार्तपरित्राणपरायणे।\nसर्वस्यार्तिहरे देवि नारायणि नमोऽस्तु ते॥",
    transliteration: "Śaraṇāgata dīnārta paritrāṇa parāyaṇe। Sarvasyārtidhare devi Nārāyaṇi namo'stu te॥",
    source_en: "Durga Saptashati (Markandeya Purana) 11.11",
    source_hi: "दुर्गा सप्तशती (मार्कण्डेय पुराण) ११.११",
    meaning_en: "O Devi, devoted to saving those who take refuge with you, the afflicted and the humble — O Narayani, remover of all suffering, salutations to you.",
    meaning_hi: "हे देवि, शरण लेने वाले दीन-पीड़ितों की रक्षा में संलग्न; हे नारायणि, सबके दुखों को हरने वाली — तुम्हें प्रणाम।",
    context_en: "Navratri Puja (nine nights of Devi worship) is the highest Shakti festival. The Durga Saptashati mandates that each of the nine nights honours one of the nine Devis: Shailputri, Brahmacharini, Chandraghanta, Kushmanda, Skandamata, Katyayani, Kalaratri, Mahagauri, and Siddhidatri. Our Pandit Ji conducts the complete Navavarana puja for each.",
    context_hi: "नवरात्रि पूजा (देवी उपासना की नौ रातें) सर्वोच्च शक्ति उत्सव है। दुर्गा सप्तशती अनिवार्य करती है कि नौ रातों में से प्रत्येक रात एक देवी को समर्पित हो।",
  },
  "diwali-puja": {
    devanagari: "लक्ष्मीं क्षीरसमुद्रराजतनयां श्रीरङ्गधामेश्वरीम्।\nदासीभूतसमस्तदेवनिकरां लोकैकदीपाङ्कुराम्॥",
    transliteration: "Lakṣmīṃ kṣīrasamudrarājatanayāṃ Śrīraṅgadhāmeśvarīm। Dāsībhūtasamastadevanikrāṃ lokaikadīpāṅkurām॥",
    source_en: "Lakshmi Ashtakam (Vedanta Desika)",
    source_hi: "लक्ष्मी अष्टकम् (वेदान्त देशिक)",
    meaning_en: "Lakshmi, daughter of the Ocean of Milk, the Goddess of Sri Ranga, she to whom all devas bow as servants — the sole lamp of the world.",
    meaning_hi: "लक्ष्मी, क्षीरसागर की पुत्री, श्रीरंगधाम की ईश्वरी, जिनकी सेवा में सभी देव लगे हैं — जगत की एकमात्र दीपशिखा।",
    context_en: "Diwali Puja (Lakshmi-Ganesh Puja on Amavasya) is the most critical puja of the financial year. According to the Skanda Purana, Lakshmi visits every home on this night — but only stays where she is welcomed with proper Shodashopachara Puja. Our Pandit Ji ensures the Pradosh Muhurat and Nishita Muhurat are correctly observed.",
    context_hi: "दीवाली पूजा (अमावस्या को लक्ष्मी-गणेश पूजा) वित्तीय वर्ष की सबसे महत्वपूर्ण पूजा है। स्कन्द पुराण के अनुसार लक्ष्मी इस रात हर घर में आती हैं — लेकिन केवल वहीं रहती हैं जहाँ उचित षोडशोपचार पूजा से उनका स्वागत किया जाए।",
  },
  "janmashtami-puja": {
    devanagari: "कृष्णाय वासुदेवाय हरये परमात्मने।\nप्रणतक्लेशनाशाय गोविन्दाय नमो नमः॥",
    transliteration: "Kṛṣṇāya Vāsudevāya Haraye Paramātmane। Praṇataklśanāśāya Govindāya namo namaḥ॥",
    source_en: "Vishnu Purana 5.18.49",
    source_hi: "विष्णु पुराण ५.१८.४९",
    meaning_en: "Salutations again and again to Krishna, Vasudeva, Hari, the Supreme Self, Govinda — the destroyer of the sorrows of all who bow to him.",
    meaning_hi: "कृष्ण, वासुदेव, हरि, परमात्मा, गोविन्द को बार-बार प्रणाम — जो शरणागतों के सभी क्लेशों का नाश करते हैं।",
    context_en: "Janmashtami Puja celebrates the birth of Sri Krishna on Bhadrapada Ashtami (midnight). The Vishnu Purana describes the exact Janmashtami Abhishek procedure — Panchamrita (milk, curd, honey, ghee, sugar) bathing of Bal-Krishna, followed by the Shodashopachar puja before the midnight birth-moment.",
    context_hi: "जन्माष्टमी पूजा भाद्रपद अष्टमी (मध्यरात्रि) को श्रीकृष्ण के जन्म का उत्सव मनाती है। विष्णु पुराण जन्माष्टमी अभिषेक की सटीक विधि बताता है।",
  },
  "maha-shivaratri": {
    devanagari: "महाशिवरात्र्यां यो जागर्ति स मुच्यते भवबन्धनात्।\nनिशि जागरणं कृत्वा शिवपूजाविधानतः॥",
    transliteration: "Mahāśivarātryāṃ yo jāgarti sa mucyate bhavabandhanāt। Niśi jāgaraṇaṃ kṛtvā śivapūjāvidhānataḥ॥",
    source_en: "Skanda Purana, Shiva Rahasya Khanda",
    source_hi: "स्कन्द पुराण, शिव रहस्य खण्ड",
    meaning_en: "One who keeps vigil on Maha Shivaratri night and performs Shiva Puja as per the prescribed procedure is freed from the bondage of worldly existence.",
    meaning_hi: "जो महाशिवरात्रि की रात जागकर विधिपूर्वक शिवपूजा करता है, वह भव-बंधन से मुक्त हो जाता है।",
    context_en: "Maha Shivaratri Puja involves four Prahars (three-hour watches) of night worship, each with a specific Abhishek and stotra. The Skanda Purana mandates: Rudrabhishek in the first Prahar, Bilva Archana in the second, Dhatura and Bhasma in the third, and Pancha Gavya in the fourth. Our Pandit Ji performs the complete four-Prahar vigil.",
    context_hi: "महाशिवरात्रि पूजा में रात के चार प्रहर (तीन-तीन घंटे) की पूजा शामिल है, प्रत्येक में विशिष्ट अभिषेक और स्तोत्र। स्कन्द पुराण आदेश देता है: पहले प्रहर में रुद्राभिषेक, दूसरे में बिल्व अर्चना, तीसरे में धतूरा और भस्म, और चौथे में पंच गव्य।",
  },
  "pitru-paksha": {
    devanagari: "तृप्यन्तु पितरः सर्वे यावन्ति पितृवंशजाः।\nश्राद्धकाले मया दत्तं तिलोदकं सहाक्षतैः॥",
    transliteration: "Tṛpyantu pitaraḥ sarve yāvanti pitṛvaṃśajāḥ। Śrāddhakāle mayā dattaṃ tilodakaṃ sahākṣataiḥ॥",
    source_en: "Garuda Purana, Shraddha Vidhi",
    source_hi: "गरुड़ पुराण, श्राद्ध विधि",
    meaning_en: "May all our ancestors be satisfied — however many there are in the ancestral lineage. I offer this Shraddha with sesame, water, and rice during the prescribed period.",
    meaning_hi: "पितृवंश में जितने भी पितर हों, वे सभी तृप्त हों। मैंने श्राद्ध काल में तिल, जल और अक्षत के साथ यह अर्पण किया है।",
    context_en: "Pitru Paksha Shraddha is the most important rite for freeing the family from Pitru Dosha. The Garuda Purana states: when Shraddha is not performed, the ancestors remain hungry souls who then cause suffering to their descendants. Our Pandit Ji performs the complete Sapindi Shraddha, Tarpan and Pind Daan.",
    context_hi: "पितृ पक्ष श्राद्ध परिवार को पितृ दोष से मुक्त करने के लिए सबसे महत्वपूर्ण अनुष्ठान है। गरुड़ पुराण कहता है: जब श्राद्ध नहीं किया जाता, तो पितर भूखी आत्माएं रहती हैं जो फिर अपने वंशजों को कष्ट देती हैं।",
  },
  "rudrachandi": {
    devanagari: "या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता।\nनमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥",
    transliteration: "Yā devī sarvabhūteṣu śaktirūpeṇa saṃsthitā। Namastasyai namastasyai namastasyai namo namaḥ॥",
    source_en: "Durga Saptashati, Chapter 5 (Devistuti)",
    source_hi: "दुर्गा सप्तशती, अध्याय ५ (देवीस्तुति)",
    meaning_en: "To that Devi who abides in all beings as Shakti (power) — salutations, salutations, salutations again and again.",
    meaning_hi: "उस देवी को नमन जो सभी प्राणियों में शक्तिरूप में विद्यमान हैं — बार-बार नमन, नमन, नमन।",
    context_en: "Rudra-Chandi is the combination of Rudra Yagna (11 Rudrabhisheks) and Chandi Havan (complete Saptashati Havan). It is one of the most powerful combined Vedic rites for removal of all obstacles, Graha doshas, and enemy troubles simultaneously. It requires a team of trained Pandits and takes two full days.",
    context_hi: "रुद्र-चण्डी रुद्र यज्ञ (11 रुद्राभिषेक) और चण्डी हवन (पूर्ण सप्तशती हवन) का संयोजन है। यह सभी बाधाओं, ग्रह दोषों और शत्रु कष्टों को एक साथ दूर करने के लिए सबसे शक्तिशाली संयुक्त वैदिक अनुष्ठानों में से एक है।",
  },
  "navchandi": {
    devanagari: "ॐ ऐं ह्रीं क्लीं चामुण्डायै विच्चे।",
    transliteration: "Oṃ aiṃ hrīṃ klīṃ cāmuṇḍāyai vicce॥",
    source_en: "Durga Saptashati Navakshari Mantra (Markandeya Purana)",
    source_hi: "दुर्गा सप्तशती नवाक्षरी मंत्र (मार्कण्डेय पुराण)",
    meaning_en: "The seed mantra of Chamunda — the Navakshari (nine-syllable) mantra that encapsulates the complete power of the Devi Bhagavata.",
    meaning_hi: "चामुण्डा का बीज मंत्र — नवाक्षरी मंत्र जो देवी भागवत की सम्पूर्ण शक्ति को समाहित करता है।",
    context_en: "Nav Chandi Yagna involves nine Pandits simultaneously reciting the complete Saptashati (700 verses) nine times in nine consecutive hours — a total of 6,300 verses in one sitting. It is prescribed for complete annihilation of family Pitra dosha and all planetary afflictions in one event.",
    context_hi: "नव चण्डी यज्ञ में नौ पंडित एक साथ नौ लगातार घंटों में पूर्ण सप्तशती (700 श्लोक) का नौ बार पाठ करते हैं — एक बैठक में कुल 6,300 श्लोक। यह परिवार के पितृ दोष और सभी ग्रह पीड़ाओं के एक ही कार्यक्रम में पूर्ण विनाश के लिए निर्धारित है।",
  },
  "satchandi": {
    devanagari: "सप्तशती पाठफलं प्राप्नोत्येव न संशयः।\nभक्त्या पठेद् यो नित्यं स मुच्यते भवबन्धनात्॥",
    transliteration: "Saptaśatī pāṭhaphalaṃ prāpnotyeva na saṃśayaḥ। Bhaktyā paṭhed yo nityaṃ sa mucyate bhavabandhanāt॥",
    source_en: "Skanda Purana, Shakti Khanda",
    source_hi: "स्कन्द पुराण, शक्ति खण्ड",
    meaning_en: "There is no doubt — the person who reads the Saptashati with devotion surely attains its complete fruit and is freed from all worldly bondage.",
    meaning_hi: "कोई संदेह नहीं — जो श्रद्धा से सप्तशती पढ़ता है, वह निश्चित ही इसका पूर्ण फल प्राप्त करता है और भव-बंधन से मुक्त हो जाता है।",
    context_en: "Sat Chandi Yagna involves six Pandits reciting the complete Saptashati seven times in six consecutive hours — a total of 4,900 verses. It is prescribed for those suffering from severe Graha doshas, business failures, and for families seeking a powerful purification before major Samskaras.",
    context_hi: "षट् चण्डी यज्ञ में छह पंडित छह लगातार घंटों में पूर्ण सप्तशती का सात बार पाठ करते हैं — कुल 4,900 श्लोक। यह गंभीर ग्रह दोष, व्यापार विफलता से पीड़ित लोगों और प्रमुख संस्कारों से पहले शक्तिशाली शुद्धिकरण की तलाश करने वाले परिवारों के लिए निर्धारित है।",
  },
  "laghu-rudra": {
    devanagari: "नमस्ते अस्तु भगवन् विश्वेश्वराय महादेवाय त्र्यम्बकाय।\nत्रिपुरान्तकाय त्रिकालाग्निकालाय कालाग्निरुद्राय॥",
    transliteration: "Namaste astu Bhagavan viśveśvarāya mahādevāya tryambakāya। Tripurāntakāya trikālāgnikālāya kālāgnīrudrāya॥",
    source_en: "Shri Rudrashtadhyayi, Laghu Rudra Stotra",
    source_hi: "श्री रुद्राष्टाध्यायी, लघु रुद्र स्तोत्र",
    meaning_en: "Salutations to you, Bhagavan Vishveshvara, Mahadeva, Tryambaka, destroyer of Tripura, fire of the three times, Kalaagni Rudra.",
    meaning_hi: "हे भगवान् विश्वेश्वर, महादेव, त्र्यम्बक, त्रिपुरान्तक, त्रिकालाग्निकाल, कालाग्निरुद्र — आपको नमन।",
    context_en: "Laghu Rudra is 11 recitations of the complete Rudrashtadhyayi (8-chapter Rudra) — a 2-day ritual. It is the prescribed remedy for Shani dosha, chronic health problems, and business obstacles. It is less intensive than Maha Rudra but more powerful than a single Rudrabhishek.",
    context_hi: "लघु रुद्र पूर्ण रुद्राष्टाध्यायी (8-अध्याय रुद्र) के 11 पाठ हैं — 2 दिवसीय अनुष्ठान। यह शनि दोष, पुराने स्वास्थ्य समस्याओं और व्यापार बाधाओं के लिए निर्धारित उपाय है।",
  },
  "namak-chamak-rudrabhishek": {
    devanagari: "नमः सोमाय च रुद्राय च नमस्ताम्राय चारुणाय च।\nनमः शङ्गाय च पशुपतये च॥",
    transliteration: "Namaḥ somāya ca rudrāya ca namastāmrāya cāruṇāya ca। Namaḥ śaṅgāya ca paśupataye ca॥",
    source_en: "Krishna Yajurveda, Taittiriya Samhita 4.5.2 (Namakam)",
    source_hi: "कृष्ण यजुर्वेद, तैत्तिरीय संहिता ४.५.२ (नमकम्)",
    meaning_en: "Salutations to Soma and Rudra; salutations to the copper-red one and the dawn-red one; salutations to the auspicious one and to Pashupati.",
    meaning_hi: "सोम और रुद्र को नमन; ताम्र और अरुण रंग के को नमन; शंग (मंगलकारी) और पशुपति को नमन।",
    context_en: "Namak-Chamak Rudrabhishek is the complete Rudrabhishek with both the Namakam (11 Anuvakas) and Chamakam (11 Anuvakas) — the most complete form of Shiva worship in the Vedic tradition. The Chamakam uniquely requests 98 different blessings from Rudra, making it the most comprehensive prosperity prayer in any religion.",
    context_hi: "नमक-चमक रुद्राभिषेक नमकम् (11 अनुवाक) और चमकम् (11 अनुवाक) दोनों के साथ पूर्ण रुद्राभिषेक है — वैदिक परंपरा में शिव उपासना का सबसे पूर्ण रूप। चमकम् अनोखे ढंग से रुद्र से 98 विभिन्न आशीर्वाद माँगता है।",
  },
  "kundli-nirman": {
    devanagari: "जन्मकाले ग्रहाः सर्वे यथा तिष्ठन्ति खेचराः।\nतन्नामजातकं प्रोक्तं तस्मात् जन्मकुण्डली॥",
    transliteration: "Janmakāle grahāḥ sarve yathā tiṣṭhanti khecarāḥ। Tannāmajātakaṃ proktaṃ tasmāt janmakuṇḍalī॥",
    source_en: "Brihat Parashari Hora Shastra 1.4",
    source_hi: "बृहत् पाराशरी होरा शास्त्र १.४",
    meaning_en: "The positions of all the wandering planets (grahas) at the time of birth — that record is called a Jataka. Therefore, the Janma Kundali.",
    meaning_hi: "जन्म के समय आकाश में भ्रमण करने वाले सभी ग्रहों की स्थिति — उस अभिलेख को जातक कहा जाता है। इसलिए जन्मकुण्डली।",
    context_en: "A Kundali (birth chart) is not superstition — it is a precise astronomical snapshot of the sky at the moment of birth. The Brihat Parashari Hora Shastra, the definitive text on Vedic astrology, prescribes how to calculate it from exact birth time, date, and place. Our Pandit Ji creates Kundalis using traditional Panchanga calculation, not software approximations.",
    context_hi: "कुंडली (जन्म कुंडली) अंधविश्वास नहीं है — यह जन्म के क्षण में आकाश का एक सटीक खगोलीय चित्र है। बृहत् पाराशरी होरा शास्त्र, वैदिक ज्योतिष का निश्चित ग्रंथ, निर्धारित करता है कि इसे सटीक जन्म समय, तिथि और स्थान से कैसे गणना करें।",
  },
  "kundli-milan": {
    devanagari: "वर्णाश्रमाचारवता पुरुषेण परः पुमान्।\nविष्णुराराध्यते पन्था नान्यत् तत्तोषकारणम्॥",
    transliteration: "Varṇāśramācāravatā puruṣeṇa paraḥ pumān। Viṣṇurārādhyate panthā nānyas tatttoṣakāraṇam॥",
    source_en: "Vishnu Purana 3.8.9",
    source_hi: "विष्णु पुराण ३.८.९",
    meaning_en: "By a person following varnashrama dharma, the Supreme Being Vishnu is worshipped — there is no other path to please Him.",
    meaning_hi: "वर्णाश्रम धर्म का पालन करने वाले पुरुष द्वारा परम पुरुष विष्णु की आराधना होती है — उन्हें प्रसन्न करने का कोई अन्य मार्ग नहीं।",
    context_en: "Kundli Milan (horoscope matching) is a 36-point compatibility analysis (Ashta-Koot Milan) that examines Varna, Vashya, Tara, Yoni, Grah Maitri, Gana, Bhakoot, and Nadi compatibility. Our Pandit Ji analyses both birth charts against the Parashari and Brihat Jataka criteria rather than relying on automated tools.",
    context_hi: "कुंडली मिलान (जन्मपत्री मिलान) 36-बिंदु अनुकूलता विश्लेषण (अष्ट कूट मिलान) है जो वर्ण, वश्य, तारा, योनि, ग्रह मैत्री, गण, भकूट और नाड़ी अनुकूलता की जाँच करता है।",
  },
  "jyotish-paramarsh": {
    devanagari: "ग्रहाणां सर्वमिदं वश्यं जगत्स्थावरजङ्गमम्।\nसुखदुःखाभिसन्धिश्च ग्रहाधीना इति स्थितिः॥",
    transliteration: "Grahāṇāṃ sarvamidaṃ vaśyaṃ jagatstāvarajaṅgamam। Sukhaduḥkhābhisandhiśca grahādhīnā iti sthitiḥ॥",
    source_en: "Brihat Jataka (Varaha Mihira) 1.2",
    source_hi: "बृहत् जातक (वराह मिहिर) १.२",
    meaning_en: "All this world — the moving and the unmoving — is subject to the planets. The union of joy and sorrow is dependent on the planets. This is the established principle.",
    meaning_hi: "यह समस्त जगत — स्थावर और जंगम — ग्रहों के अधीन है। सुख-दुःख का संगम ग्रहाधीन है। यही सिद्धांत है।",
    context_en: "Jyotish Paramarsh (Vedic astrology consultation) with our Pandit Ji uses the Parashari and Jaimini systems — the same two systems used by every classical Jyotishi for 2,000 years. The consultation includes full Lagna (ascendant) chart analysis, Nakshatra Dasha analysis, and specific remedies.",
    context_hi: "हमारे पंडित जी के साथ ज्योतिष परामर्श पाराशरी और जैमिनी प्रणालियों का उपयोग करता है — वही दो प्रणालियाँ जो 2,000 वर्षों से हर शास्त्रीय ज्योतिषी द्वारा उपयोग की जाती हैं।",
  },
  "vastu-paramarsh": {
    devanagari: "वास्तुशास्त्रं प्रवक्ष्यामि समस्तजगदुत्तमम्।\nयस्य ज्ञानमात्रेण सर्वसिद्धिर्भवेद्ध्रुवम्॥",
    transliteration: "Vāstuśāstraṃ pravakṣyāmi samastajagaduttamam। Yasya jñānamātreṇa sarvasiddhirbhaveddhruvam॥",
    source_en: "Vishvakarma Vastu Shastra 1.1",
    source_hi: "विश्वकर्मा वास्तु शास्त्र १.१",
    meaning_en: "I shall expound the Vastu Shastra — supreme in all the world. By its knowledge alone, all success surely comes.",
    meaning_hi: "मैं वास्तु शास्त्र का उपदेश दूँगा — जो समस्त जगत में श्रेष्ठ है। केवल इसके ज्ञान से ही सभी सिद्धियाँ निश्चित रूप से प्राप्त होती हैं।",
    context_en: "Vastu Paramarsh (consultation) involves a systematic analysis of your home or office using the eight Vastu Directions (Ashtadisha), the Vastu Purusha Mandala, and the Panchabhoota theory. Our Pandit Ji uses the Vishvakarma Vastu Shastra and Manasara as the primary references — not internet-based approximations.",
    context_hi: "वास्तु परामर्श में आठ वास्तु दिशाओं (अष्टदिशा), वास्तु पुरुष मण्डल और पंचभूत सिद्धांत का उपयोग करते हुए आपके घर या कार्यालय का व्यवस्थित विश्लेषण शामिल है।",
  },
  "antim-sanskar": {
    devanagari: "आत्मा वा इदं एक एवाग्र आसीत्। नान्यत् किञ्चन मिषत्।\nस ईक्षत लोकान्नु सृजा इति॥",
    transliteration: "Ātmā vā idaṃ eka evāgra āsīt। Nānyat kiñcana miṣat। Sa īkṣata lokānnu sṛjā iti॥",
    source_en: "Aitareya Upanishad 1.1.1",
    source_hi: "ऐतरेय उपनिषद् १.१.१",
    meaning_en: "In the beginning, the Atman alone existed — nothing else at all. He thought: let me create the worlds.",
    meaning_hi: "सृष्टि के प्रारंभ में केवल आत्मा थी — और कुछ नहीं। उसने विचार किया: मैं लोकों की सृष्टि करूँ।",
    context_en: "Antim Sanskar (last rites) is the 16th and final Samskara — returning the Pancha Bhoota (five elements) of the body to their source. The Garuda Purana prescribes exact timings, mantras and procedures for Asthi Visarjan, Shraddha, and Pind Daan. Our Pandit Ji guides the family through every step with compassion and scriptural precision.",
    context_hi: "अंतिम संस्कार (अंत्येष्टि) 16वाँ और अंतिम संस्कार है — शरीर के पंचभूतों को उनके स्रोत पर वापस करना। गरुड़ पुराण अस्थि विसर्जन, श्राद्ध और पिंड दान के लिए सटीक समय, मंत्र और प्रक्रियाएं निर्धारित करता है।",
  },
};
